# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XrCCIE0vHmr8H0rKWGWKGCA5TRLJ7CW5
"""

import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)

type(my_array)

range_array = np.arange(1, 10, 2)
print(range_array)

my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_array = np.array(my_list)
print(my_array)

zeros_array = np.zeros((3, 4))
print(zeros_array)

ones_array = np.ones((2, 3))
print(ones_array)

linspace_array=np.linspace(0,1,10)
print(linspace_array)

full_array=np.full((3,5), 3)
print(full_array)

random_randint_array=np.random.randint(0,10, (3,3))
print(random_randint_array)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Boyut Sayisi:", arr.ndim)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Boyut Bilgisi:", arr.shape)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Toplam Eleman Sayısı:", arr.size)

arr = np.array([1, 2, 3])
print("Dizi Veri Tipi:", arr.dtype)

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)

print("Orijinal Dizi:")
print(arr)
print("Yeniden Şekillendirilmiş Dizi:")
print(reshaped_arr)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.concatenate((arr1, arr2))

print("Birleştirilmiş Dizi:")
print(result)

arr = np.array([1, 2, 3, 4, 5, 6])
result = np.split(arr, 3)

print("Bölünmüş Diziler:")
for sub_array in result:
    print(sub_array)

arr = np.array([3, 1, 5, 2, 4])
sorted_indices = arr.argsort()
sorted_arr = arr[sorted_indices]

print("Sıralanmış Dizi:")
print(sorted_arr)

arr = np.array([1, 2, 3, 4, 5])
element = arr[2]

print("Eleman:", element)

import numpy as np

# Toplama
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_result = np.add(arr1, arr2)
print("Toplama Sonucu:", sum_result)

# Çıkarma
arr1 = np.array([4, 5, 6])
arr2 = np.array([1, 2, 3])
sub_result = np.subtract(arr1, arr2)
print("Çıkarma Sonucu:", sub_result)

# Çarpma
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
mul_result = np.multiply(arr1, arr2)
print("Çarpma Sonucu:", mul_result)

# Bölme
arr1 = np.array([4, 6, 8])
arr2 = np.array([2, 2, 2])
div_result = np.divide(arr1, arr2)
print("Bölme Sonucu:", div_result)

# Üs alma
arr = np.array([2, 3, 4])
power_result = np.power(arr, 3)
print("Üs Alma Sonucu:", power_result)

import numpy as np

# Sinüs
arr = np.array([0, np.pi/2, np.pi])
sin_result = np.sin(arr)
print("Sinüs Sonucu:", sin_result)

# Kosinüs
arr = np.array([0, np.pi/2, np.pi])
cos_result = np.cos(arr)
print("Kosinüs Sonucu:", cos_result)

# Tanjant
arr = np.array([0, np.pi/4, np.pi/2])
tan_result = np.tan(arr)
print("Tanjant Sonucu:", tan_result)

import numpy as np

# Logaritma
arr = np.array([1, 10, 100])
log_result = np.log(arr)
print("Logaritma Sonucu:", log_result)

# Karekök
arr = np.array([4, 9, 16])
sqrt_result = np.sqrt(arr)
print("Karekök Sonucu:", sqrt_result)

# Üstel Fonksiyon
arr = np.array([2, 3, 4])
exp_result = np.exp(arr)
print("Üstel Fonksiyon Sonucu:", exp_result)

import numpy as np

# Ortalama
arr = np.array([1, 2, 3, 4, 5])
mean_result = np.mean(arr)
print("Ortalama:", mean_result)

# Standart Sapma
arr = np.array([1, 2, 3, 4, 5])
std_result = np.std(arr)
print("Standart Sapma:", std_result)

# Minimum Değer
arr = np.array([1, 2, 3, 4, 5])
min_result = np.min(arr)
print("Minimum Değer:", min_result)

# Maksimum Değer
arr = np.array([1, 2, 3, 4, 5])
max_result = np.max(arr)
print("Maksimum Değer:", max_result)