# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18qgbZQH2lGUcpn_v9OyoASnL_oO4iIma
"""

#kütüphane import etme
import numpy as np

#veri okuma
df = pd.read_csv("veri_dosyasinin_adi.csv")

import pandas as pd

# Örnek verileri tanımlama
data = {
    'İsim': ['Ahmet', 'Mehmet', 'Ayşe', 'Fatma'],
    'Yaş': [25, 30, 28, 35],
    'Şehir': ['İstanbul', 'Ankara', 'İzmir', 'Bursa']
}

# DataFrame oluşturma
df = pd.DataFrame(data)

# DataFrame'i görüntüleme
print(df)

pd.DataFrame(data, columns = ["İsim"])

df = pd.DataFrame(data, columns = ["İsim","Yaş","Şehir"])
df.head()

df.axes

df.shape

df.ndim

df.size

df.values

df.tail(1)

import numpy as np
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

sozluk = {"var1": s1, "var2": s2, "var3": s3}
sozluk

df = pd.DataFrame(sozluk)
df

df[0:1]

df.index = ["a","b","c","d","e"]

df.drop("a", axis = 0, inplace = True)
df

"var1" in df

df["var4"] = df["var1"] / df["var2"]  
df

import pandas as pd

data = {'A': [1, 2, 3],
        'B': [4, 5, 6],
        'C': [7, 8, 9]}

df = pd.DataFrame(data, index=['x', 'y', 'z'])

# 'x' indeksine sahip satırı seçme
df.loc['x']

# 'A' sütununu seçme
df.loc[:, 'A']

# 'x' indeksine sahip satırın 'B' ve 'C' sütunlarını seçme
df.loc['x', ['B', 'C']]

import pandas as pd

data = {'A': [1, 2, 3],
        'B': [4, 5, 6],
        'C': [7, 8, 9]}

df = pd.DataFrame(data)

# İlk satırı seçme
df.iloc[0]

# İlk sütunu seçme
df.iloc[:, 0]

# İlk satırın ikinci ve üçüncü sütunlarını seçme
df.iloc[0, 1:3]

import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

df[df.var1 > 15]

df[(df.var1 > 15) & (df.var3 < 10)]

df

df2 = df + 99
df2

pd.concat([df,df2])

import pandas as pd

df1 = pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],
                    'grup': ['Muhasebe', 'Muhendislik', 'Muhendislik', 'İK']})

df1

df2 = pd.DataFrame({'calisanlar': ['Ayse', 'Ali', 'Veli', 'Fatma'],
                    'ilk_giris': [2010, 2009, 2014, 2019]})

df2

df1

df2

pd.merge(df1, df2)

import pandas as pd

# Örnek bir veri çerçevesi oluşturalım
data = {
    'Grup': ['A', 'B', 'A', 'B', 'A'],
    'Değer': [10, 15, 20, 25, 30]
}
df = pd.DataFrame(data)
grouped=df.groupby('Grup')
aggregated = grouped.sum()
aggregated